# FOSSA Configuration
# https://github.com/fossas/fossa-cli/blob/master/docs/references/files/fossa-yml.md

version: 3

project:
  id: github.com/NullPointerDepressiveDisorder/MiddleDrag

targets:
  only:
    - type: xcode
      path: MiddleDrag.xcodeproj

# Exclude directories that shouldn't be scanned
paths:
  exclude:
    - build/
    - .build/
    - DerivedData/
    - TestResults.xcresult/
