# FOSSA Configuration
# https://github.com/fossas/fossa-cli/blob/master/docs/references/files/fossa-yml.md

version: 3

project:
  name: MiddleDrag

# Let FOSSA auto-discover Package.resolved
# Exclude directories that shouldn't be scanned
paths:
  exclude:
    - build/
    - .build/
    - DerivedData/
    - TestResults.xcresult/
