# Codecov Configuration for MiddleDrag
# https://docs.codecov.io/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: false
        if_ci_failed: error
        if_not_found: failure
    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error
        informational: false
        branches:
          - "master"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: true

ignore:
  - "**/MiddleDragTests/**"
  - "**/AppDelegate.swift"
  - "**/MiddleDragApp.swift"
  - "**/Assets.xcassets/**"
  - "**/UpdateManager.swift"

flags:
  Unit-Tests:
    after_n_builds: 1

github_checks:
  annotations: true
